name: Build LuaRocks module for Tarantool

on: [push, pull_request]

jobs:
  build:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: checkout modern-tarantool-lua-template
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install tarantool build prerequisites for Mac
        if: runner.os == 'macOS'
        run: |
          brew install msgpuck luajit luarocks

      - name: Install tarantool build prerequisites for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y luarocks libmsgpuck-dev libluajit-5.1-dev

      - name: luarocks make and pack
        run: |
          luarocks make --local
          luarocks pack --local modern-tarantool-lua-template

      - name: publishing linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: modern-tarantool-lua-template-scm-1.linux-x86_64.rock
          path: modern-tarantool-lua-template-scm-1.linux-x86_64.rock

      - name: publishing macosx artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: modern-tarantool-lua-template-scm-1.macosx-x86_64.rock
          path: modern-tarantool-lua-template-scm-1.macosx-x86_64.rock
